version: "3.9"

services:
  controller_module:
    image: controller_module
    build:
      context: ./controller_module
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - analyze_module
      - search_module
     networks:
       - analyze
       - password
     
  analyze_module:
    image: analyze_module
    build:
      context: ./analyze_module
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
     networks:
      - analyze
     volumes:
        - ./theHarvester/:/home/code/psaa

 password_module:
    image: password_module
    build:
      context: ./password_module
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - password
    volumes:
        - ./theHarvester/:/home/code/psaa

rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 5673:5672

networks:
    analyze:
    password: