version: "3.9"

services:
  controller_module:
    image: controller_module
    build:
      context: ./controller_module
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./theHarvester:/home/code/theHarvester
    networks:
      - password
      - analyze
         
  analyze_module:
    image: analyze_module
    build:
      context: ./analyze_module
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./theHarvester:/home/code/theHarvester
    networks:
      - analyze

  password_module:
    image: password_module
    build:
      context: ./password_module
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./theHarvester:/home/code/theHarvester
    networks:
      - password

  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 127.0.0.1:5672:5672
    networks:
      - analyze
      - password
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics is_running"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  analyze:
    name: analyze
    driver: bridge
  password:
    name: password
    driver: bridge