version: "3.9"

services:
  controller_module:
    image: controller_module
    build:
      context: ./controller_module
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - analyze_module
      - password_module
    volumes:
      - ./theHarvester:/home/code/theHarvester
    networks:
      - password
      - analyze
         
  analyze_module:
    image: analyze_module
    build:
      context: ./analyze_module
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./theHarvester:/home/code/theHarvester
    networks:
      - analyze

  password_module:
    image: password_module
    build:
      context: ./password_module
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./theHarvester:/home/code/theHarvester
    networks:
     - password

  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 5673:5672
    networks:
      - analyze
      - password

networks:
  analyze:
    name: analyze
    driver: bridge
  password:
    name: password
    driver: bridge